# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-15 17:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0014_auto_20160604_0007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='name',
            field=models.CharField(choices=[('Trello', 'Trello'), ('Github', 'Github'), ('Bitbucket', 'Bitbucket'), ('Slack', 'Slack'), ('Google Apps', 'Google Apps'), ('Jira', 'Jira'), ('HipChat', 'HipChat')], max_length=50),
        ),
    ]
