# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-16 16:36
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0015_auto_20160615_1734'),
    ]

    operations = [
        migrations.CreateModel(
            name='ErrorLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=datetime.datetime.now)),
                ('text', models.TextField()),
            ],
            options={
                'ordering': ('-timestamp',),
            },
        ),
        migrations.AlterField(
            model_name='service',
            name='name',
            field=models.CharField(choices=[('Trello', 'Trello'), ('Github', 'Github'), ('Bitbucket', 'Bitbucket'), ('Slack', 'Slack'), ('Jira', 'Jira'), ('HipChat', 'HipChat')], max_length=50),
        ),
        migrations.AddField(
            model_name='errorlog',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service', to='team.Service'),
        ),
        migrations.AddField(
            model_name='errorlog',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team', to='team.Team'),
        ),
        migrations.AddField(
            model_name='errorlog',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teamuser', to=settings.AUTH_USER_MODEL),
        ),
    ]
