# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-21 19:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0016_auto_20160616_1636'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='name',
            field=models.CharField(choices=[('HipChat', 'HipChat'), ('Trello', 'Trello'), ('Jira', 'Jira'), ('Bitbucket', 'Bitbucket'), ('Slack', 'Slack'), ('Github', 'Github')], max_length=50),
        ),
    ]
