# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-24 13:10
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0017_auto_20160621_1928'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='admin',
            field=models.ManyToManyField(related_name='admin', to=settings.AUTH_USER_MODEL),
        ),
    ]
