# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-01 22:09
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0018_team_admin'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdditionalInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.CharField(blank=True, max_length=255)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_info', to='team.Service')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_info', to='team.Team')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teamuser_info', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
