# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-29 13:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0019_additionalinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='name',
            field=models.CharField(choices=[('Toggl', 'Toggl'), ('HipChat', 'HipChat'), ('Zendesk', 'Zendesk'), ('Trello', 'Trello'), ('Jira', 'Jira'), ('Asana', 'Asana'), ('Box', 'Box'), ('Dropbox', 'Dropbox'), ('Bitbucket', 'Bitbucket'), ('Slack', 'Slack'), ('Quay', 'Quay'), ('Github', 'Github')], max_length=50),
        ),
    ]
