# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-02 20:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0020_auto_20160729_1312'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='org_limit',
            field=models.IntegerField(default=0),
        ),
    ]
