# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-09-22 14:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0022_auto_20160914_2136'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='description',
            field=models.CharField(default='Sample Team Description', max_length=1024),
            preserve_default=False,
        ),
    ]
