# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-09-22 15:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0022_auto_20160914_2136'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='description',
            field=models.CharField(default='sample description', max_length=1024),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='service',
            name='name',
            field=models.CharField(choices=[(b'Quay', b'Quay'), (b'Box', b'Box'), (b'Asana', b'Asana'), (b'Jira', b'Jira'), (b'Toggl', b'Toggl'), (b'Zendesk', b'Zendesk'), (b'Bitbucket', b'Bitbucket'), (b'Trello', b'Trello'), (b'HipChat', b'HipChat'), (b'Dropbox', b'Dropbox'), (b'Slack', b'Slack'), (b'Github', b'Github')], max_length=50),
        ),
    ]
