# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-09-27 16:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0023_team_description'),
        ('team', '0023_auto_20160922_1534'),
    ]

    operations = [
    ]
