# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-10-07 11:59
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0024_merge'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='invited',
            field=models.ManyToManyField(blank=True, related_name='team_invited', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='service',
            name='name',
            field=models.CharField(choices=[(b'Toggl', b'Toggl'), (b'Github', b'Github'), (b'Jira', b'Jira'), (b'Asana', b'Asana'), (b'Bitbucket', b'Bitbucket'), (b'Trello', b'Trello'), (b'Zendesk', b'Zendesk'), (b'Quay', b'Quay'), (b'Box', b'Box'), (b'HipChat', b'HipChat'), (b'Dropbox', b'Dropbox'), (b'Slack', b'Slack')], max_length=50),
        ),
    ]
