# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-09-14 21:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Trello', 'Trello'), ('Github', 'Github'), ('Bitbucket', 'Bitbucket'), ('Slack', 'Slack'), ('Google Apps', 'Google Apps'), ('Jira', 'Jira'), ('HipChat', 'HipChat')], max_length=50)),
                ('token', models.CharField(blank=True, max_length=200, null=True)),
                ('org_name', models.CharField(blank=True, max_length=200, null=True)),
                ('team_name', models.CharField(blank=True, max_length=200, null=True)),
                ('team_id', models.CharField(blank=True, max_length=200, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
